### ISSUE TITLE
[trajets.lotocar] Ne plus afficher le nombre de minutes de détour

### ISSUE THREAD

**Issue by DavidBruant** [DavidBruant/lotocar#102]
Ne rien écrire si le trajet est exact
écrire un truc genre "le.a conducteur.rice va peut-être faire un détour mineur" quand c'est le cas

**Comment by laem** [comment]
Je suis circonspect à ce sujet. 
Il a clairement un problème avec l'implémentation actuelle, mais je pense que le détour est une information importante.
La cible de Lotocar n'est pas seulement le trajet domicile-travail régulier, pour lequel un détour important n'est pas acceptable. Si j'ai bien compris, c'est aussi un moyen de rejoindre une ville par exemple le weekend. Or dans ces cas-là, savoir qu'un départ est possible à 20 minutes d'où je fais ma recherche peut être une information très intéressante. Par exemple, si un bus peut m'amener de l'autre côté de la ville, ce trajet m'intéresse. Ou encore, je pourrais tenter du stop pour y aller.

L'autre jour quand j'ai voulu rejoindre Montpellier depuis Cahors, via Blablacar, c'était très frustrant de devoir tenter toutes les villes du coin (à la fois au départ qu'à l'arrivée d'ailleurs). 

En bref, le détour en minutes me semble être une information qui sert d'indication pour un trajet multimodal (en l'absence d'un algorithme complet).

**Comment by laem** [comment]
Discussion avec @sabinesafi, apparemment le détour est souvent sous-estimé d'après les retours utilisateur. 
@DavidBruant tu penses qu'on peut augmenter un peu le ratio `STRAIGHT_LINE_TO_ROAD_DISTANCE_RATIO` ?

**Comment by laem** [comment]
J'ai commencé un peu le travail décrit dans mon commentaire sur #105
