### ISSUE TITLE
Ptèt que les analytics sont comptées aussi en dev

### ISSUE THREAD

**Issue by DavidBruant** [DavidBruant/lotocar#111]
Et ptèt aussi sur lotocar-demo
Chuis pas 100% sûr. Mais si c'est le cas, ça vaudrait le coup d'y remédier plutôt rapidement que lentement

**Comment by laem** [comment]
![Screenshot_20191212-100754_Brave](https://user-images.githubusercontent.com/1177762/70698222-4e8aa480-1cc7-11ea-9688-7f1ab7be85ff.jpg)

**Comment by laem** [comment]
À vérifier, mais normalement la conf exclut le dev

**Comment by DavidBruant** [comment]
ah trop cool
je m'attendais à ce que ça aie une empreinte sur le code, j'avais pas envisagé que ça pourrait se régler via une config Matomo

a priori, ça devrait être bon, je ferme l'issue. On pourra en réouvrir si vraiment on constate que y'a un danger sur ce sujet
