### ISSUE TITLE
outil propose des trajets qui n'ont rien à voir avec la demande

### ISSUE THREAD

**Issue by Nathalielotocar** [DavidBruant/lotocar#32]
Exemple Cahors Girac

1 ère propostion un trajet totalement incohérent avec 11 minutes de détours annoncé alors que le trajet est totalement différent

**Comment by DavidBruant** [comment]
L'outil utilise actuellement 2 systèmes qui font correspondre des noms à des positions géographiques : la [Base d'Adresses Nationale (BAN)](https://api.gouv.fr/api/base-adresse-nationale.html) et l'API Directions de Google Maps
Les calculs de trajets se font actuellement avec les positions fournies par la BAN et les dessins de trajets se font via l'API Google Maps

Dans ce cas-ci, l'arrivée du trajet conducteur est `Cahors (Pradines)`. La BAN interprète ce lieu comme la commune de Pradines près de Rouanne (vers Lyon). De son côté, Google Maps utilise la ville de Pradines dans le Lot. D'où la très mauvaise indication sur l'interface.

Côté solution, je crois que je vais choisir de n'utiliser que la BAN (+règles spécifiques à Lotocar notamment pour les noms de villages fusionnés #20 ) pour la résolution de nom et passer uniquement des positions (latitude/longitude) à l'API Directions. Ça ne va pas résoudre tous les problèmes d'incompréhensions de nom, mais au moins, ça permettra que l'interface soit toujours cohérente

**Comment by DavidBruant** [comment]
A priori, ce problème est résolu. La nouvelle version de l'outil corrigé sera en ligne dans quelques minutes
Désormais, toutes les positions géographiques sont fournies par [l'API géo](https://geo.api.gouv.fr/)

C'est à vérifier, mais j'ai l'impression que cette correction est en demi-mesure : le problème de trajet qui n'ont rien à voir est a priori corrigé, mais c'est au "prix" de rendre plus explicite le fait que certaines communes saisies par les conducteur.rice.s ne sont pas comprises par les outils que j'utilise pour trouver les positions "GPS"
C'est un problème qui était déjà existant (#34 ) et a un peu gonflé
