### ISSUE TITLE
Remplacer l'implémentation de l'autocomplete actuel par un <datalist>

### ISSUE THREAD

**Issue by DavidBruant** [DavidBruant/lotocar#78]
(seulement une proposition à ce stade)
C'est sûrement plus simple à coder et c'est [standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist), donc on surfe sur la vague du taf UX du navigateur

**Comment by laem** [comment]
Intéressant, je ne connaissais pas !
