### ISSUE TITLE
Faire comprendre qu'il faut cliquer sur la destination pour qu'elle soit prise en compte

### ISSUE THREAD

**Issue by IshanB** [DavidBruant/lotocar#81]
J'ai galéré à comprendre qu'il fallait cliquer sur le nom de la ville pour l'origine et la destination afin que le moteur de recherche le prenne en compte, du coup je suis resté bloqué sur cet écran sans comprendre ce qui était attendu de moi : 

![image](https://user-images.githubusercontent.com/28890473/68413107-d6900280-018d-11ea-9348-576607b1ee06.png)

**Comment by DavidBruant** [comment]
yes. Je pense qu'on va le corriger via #78

**Comment by laem** [comment]
Je pense qu'on peut sélectionner automatiquement la ville quand il n'yen a qu'une seule. Tu n'aurais pas eu ce problème s'il y avait au moins 2 choix.

**Comment by laem** [comment]
Autre problème : après une recherche réussie, si on veut revenir changer la ville de destination, il faut aussi revalider le départ. Pas cool.
