### ISSUE TITLE
Demandes passagers via Lotocar : donner le choix formulaire ou téléphone

### ISSUE THREAD

**Issue by sabinesafi** [DavidBruant/lotocar#85]
ETQ passagère qui trouve un trajet qui me convient et pour lequel je dois passer par Lotocar pour contacter le conducteur : 
Actuellement, je ne peux que téléphoner à Lotocar et réexpliquer toute ma recherche, c'est pas très gérable pour Nathalie et ça peut me rebuter d'être obligée d'appeler.
Je souhaite avoir le choix entre appeler Lotocar ou remplir le formulaire de demande passager (beaucoup plus gérable pour Nathalie en asynchrone et avec toutes les infos).

Question mark: quand je décide de contacter Lotocar, j'ai déjà choisi le(s) conducteur(s) qui m'intéresse(nt) or le formulaire actuel demandera à Nathalie de refaire toute la recherche sans tenir compte du trajet que j'ai déjà repéré. (peut-être qu'on peut écrire le nom du conducteur dans le formulaire via les paramètres de l'URL ? ou autre...)

**Comment by laem** [comment]
Pour cela j'imagine une interface du style panneau plein écran : 

```
- contacter un humain
- faire une demande en ligne
```

**Comment by sabinesafi** [comment]
Ok pour moi :)
