### ISSUE TITLE
Problème spécifique sur Kiwi 

### ISSUE THREAD

**Issue by laem** [DavidBruant/lotocar#90]
![Screenshot_20191108-140245_Kiwi Browser](https://user-images.githubusercontent.com/1177762/68478559-7f8f3980-0230-11ea-9fe7-fff4912260fd.jpg)

**Comment by DavidBruant** [comment]
flat est une fonction moderne
Elle n'est peut-être pas supportée
Il suffit sûrement de rajouter des polyfills ([décommenter](https://github.com/DavidBruant/lotocar/blob/master/direct/index.html#L17-L19) peut marcher ; à vérifier)

**Comment by laem** [comment]
C'est étrange car Kiwi n'est qu'une distribution d'une version de Chrome moderne qui supporte .flat.
J'en déduis que les navigateurs basés sur chromium peuvent choisir d'activer un niveau personnalisé de fonctionnalités du moteur JS.
On peut en effet utiliser polyfill.io, ou simplement utiliser l'équivalent de la fonction chez Lodash.
