### ISSUE TITLE
[outil métier] Ne pas afficher les trajets sans retour

### ISSUE THREAD

**Issue by lotocar** [DavidBruant/lotocar#97]
L'outil que j'utilise pour les recherches de trajets ne tient pas compte de certaines modifs faites dans la base de données concernant les retours Ex Albas - Cahors avec Clémence H  ou Limoges - Flaujac-Poujols avec Laurent B

**Comment by DavidBruant** [comment]
On a résolu ce truc-là dans trajets.lotocar
Mais le code côté serveur de l'outil métier n'est plus le même
Ptèt mutualiser ce code
